const Carta = [
  {
    id: 1,
    nombrePlato: "Pollo al Champiñon",
    descripcion: "...",
    precio: 6700,
    categoria: "Aves",
  },
  {
    id: 2,
    nombrePlato: "Pollo a la Plancha",
    descripcion: "...",
    precio: 3800,
    categoria: "Aves",
  },
  {
    id: 3,
    nombrePlato: "Suprema",
    descripcion: "...",
    precio: 4200,
    categoria: "Aves",
  },
  {
    id: 4,
    nombrePlato: "Suprema Napolitana",
    descripcion: "...",
    precio: 4900,
    categoria: "Aves",
  },
  {
    id: 5,
    nombrePlato: "Chop Suey de Pollo",
    descripcion: "...",
    precio: 5900,
    categoria: "Aves",
  },
  {
    id: 6,
    nombrePlato: "Pechuga Rellena de Espinaca y Queso",
    descripcion: "...",
    precio: 6700,
    categoria: "Aves",
  },
  {
    id: 7,
    nombrePlato: "Pollo al Ajillo",
    descripcion: "...",
    precio: 6700,
    categoria: "Aves",
  },
  {
    id: 8,
    nombrePlato: "Abadejo con Salsa de Verdeo",
    descripcion: "...",
    precio: 8800,
    categoria: "Pescado",
  },
  {
    id: 9,
    nombrePlato: "Abadejo con Salsa Roquefort",
    descripcion: "...",
    precio: 8800,
    categoria: "Pescado",
  },
  {
    id: 10,
    nombrePlato: "Abadejo con Salsa Camarones",
    descripcion: "...",
    precio: 10600,
    categoria: "Pescado",
  },
  {
    id: 11,
    nombrePlato: "Salmon a la Plancha",
    descripcion: "...",
    precio: 12000,
    categoria: "Pescado",
  },
  {
    id: 12,
    nombrePlato: "Chop Suey de Salmon",
    descripcion: "...",
    precio: 13900,
    categoria: "Pescado",
  },
  {
    id: 13,
    nombrePlato: "Salmon Grille",
    descripcion: "...",
    precio: 16300,
    categoria: "Pescado",
  },
  {
    id: 14,
    nombrePlato: "Salmon con salsa Teriyaki",
    descripcion: "...",
    precio: 14100,
    categoria: "Pescado",
  },
  {
    id: 15,
    nombrePlato: "Pulpo la porcion",
    descripcion: "...",
    precio: 20900,
    categoria: "Pescado",
  },
  {
    id: 16,
    nombrePlato: "Pulpo y Langostinos a la parrilla Adobado",
    descripcion: "...",
    precio: 21700,
    categoria: "Pescado",
  },
  {
    id: 17,
    nombrePlato: "Salsa de Camarones",
    descripcion: "...",
    precio: 5500,
    categoria: "Pescado",
  },
  {
    id: 18,
    nombrePlato: "Matambrito de Cerdo",
    descripcion: "...",
    precio: 6600,
    categoria: "Sugerencias de Nuestro Chef",
  },
  {
    id: 19,
    nombrePlato: "Brochette de Lomo",
    descripcion: "...",
    precio: 7000,
    categoria: "Sugerencias de Nuestro Chef",
  },
  {
    id: 20,
    nombrePlato: "Entraña",
    descripcion: "...",
    precio: 8800,
    categoria: "Sugerencias de Nuestro Chef",
  },
  {
    id: 21,
    nombrePlato: "Milanesa",
    descripcion: "...",
    precio: 4100,
    categoria: "Carnes",
  },
  {
    id: 22,
    nombrePlato: "Milanesa Napolitana",
    descripcion: "...",
    precio: 4700,
    categoria: "Carnes",
  },
  {
    id: 23,
    nombrePlato: "Lomo a la Plancha",
    descripcion: "...",
    precio: 4600,
    categoria: "Carnes",
  },
  {
    id: 24,
    nombrePlato: "Chop Suey de Lomo",
    descripcion: "...",
    precio: 6200,
    categoria: "Carnes",
  },
  {
    id: 25,
    nombrePlato: "Lomo a la Panceta",
    descripcion: "...",
    precio: 7900,
    categoria: "Carnes",
  },
  {
    id: 26,
    nombrePlato: "Lomo al Champignon",
    descripcion: "...",
    precio: 7900,
    categoria: "Carnes",
  },
  {
    id: 27,
    nombrePlato: "Lomo a la Pimienta",
    descripcion: "...",
    precio: 7500,
    categoria: "Carnes",
  },
  {
    id: 28,
    nombrePlato: "Lomo al Verdeo",
    descripcion: "...",
    precio: 7500,
    categoria: "Carnes",
  },
  {
    id: 29,
    nombrePlato: "Lomo Strogonoff",
    descripcion: "...",
    precio: 7500,
    categoria: "Carnes",
  },
  {
    id: 30,
    nombrePlato: "Lomo Ragu de Hongos",
    descripcion: "...",
    precio: 7900,
    categoria: "Carnes",
  },
  {
    id: 31,
    nombrePlato: "Saltimbocca a la Romana",
    descripcion: "...",
    precio: 7500,
    categoria: "Carnes",
  },
  {
    id: 32,
    nombrePlato: "Empanada de Carne cortada a cuchillo",
    descripcion: "...",
    precio: 650,
    categoria: "Entradas de Mesa",
  },
  {
    id: 33,
    nombrePlato: "Rabas",
    descripcion: "...",
    precio: 5800,
    categoria: "Entradas de Mesa",
  },
  {
    id: 34,
    nombrePlato: "Gambas al Ajillo",
    descripcion: "...",
    precio: 8000,
    categoria: "Entradas de Mesa",
  },
  {
    id: 35,
    nombrePlato: "Provoleta Quatroccento",
    descripcion: "...",
    precio: 2800,
    categoria: "Entradas de Mesa",
  },
  {
    id: 36,
    nombrePlato: "Picada de Mariscos",
    descripcion: "...",
    precio: 15300,
    categoria: "Entradas de Mesa",
  },
  {
    id: 37,
    nombrePlato: "Carpaccio de Salmon",
    descripcion: "...",
    precio: 7600,
    categoria: "Entradas de Mesa",
  },
  {
    id: 38,
    nombrePlato: "Milanesa de Mozarella",
    descripcion: "...",
    precio: 2700,
    categoria: "Entradas de Mesa",
  },
  {
    id: 39,
    nombrePlato: "Huevo Frito",
    descripcion: "...",
    precio: 500,
    categoria: "Guarnicion",
  },
  {
    id: 40,
    nombrePlato: "Papas Fritas",
    descripcion: "...",
    precio: 2200,
    categoria: "Guarnicion",
  },
  {
    id: 41,
    nombrePlato: "Papas Españolas",
    descripcion: "...",
    precio: 2200,
    categoria: "Guarnicion",
  },
  {
    id: 42,
    nombrePlato: "Pure de Papas",
    descripcion: "...",
    precio: 2200,
    categoria: "Guarnicion",
  },
  {
    id: 43,
    nombrePlato: "Pure de Calabaza",
    descripcion: "...",
    precio: 2200,
    categoria: "Guarnicion",
  },
  {
    id: 44,
    nombrePlato: "Papas a la Crema",
    descripcion: "...",
    precio: 2500,
    categoria: "Guarnicion",
  },
  {
    id: 45,
    nombrePlato: "Papas Fritas con Huevo",
    descripcion: "...",
    precio: 2500,
    categoria: "Guarnicion",
  },
  {
    id: 46,
    nombrePlato: "Panache de Verduras",
    descripcion: "...",
    precio: 2800,
    categoria: "Guarnicion",
  },
  {
    id: 47,
    nombrePlato: "Tortilla de Papa",
    descripcion: "...",
    precio: 5000,
    categoria: "Guarnicion",
  },
  {
    id: 48,
    nombrePlato: "Ensaladas de Hojas Verdes",
    descripcion: "...",
    precio: 2500,
    categoria: "Ensaladas",
  },
  {
    id: 49,
    nombrePlato: "Ensalada Mixta",
    descripcion: "...",
    precio: 2500,
    categoria: "Ensaladas",
  },
  {
    id: 50,
    nombrePlato: "Ensalada Quatroccento",
    descripcion: "...",
    precio: 4000,
    categoria: "Ensaladas",
  },
  {
    id: 51,
    nombrePlato: "Ensalada Cesar",
    descripcion: "...",
    precio: 4400,
    categoria: "Ensaladas",
  },
  {
    id: 52,
    nombrePlato: "Costilla de Cerdo a la Barcacoa",
    descripcion: "...",
    precio: 6600,
    categoria: "Cerdos",
  },
  {
    id: 53,
    nombrePlato: "Chop Suey de Cerdo",
    descripcion: "...",
    precio: 5300,
    categoria: "Cerdos",
  },
  {
    id: 54,
    nombrePlato: "Carre con Compota de Ciruela",
    descripcion: "...",
    precio: 5300,
    categoria: "Cerdos",
  },
  {
    id: 55,
    nombrePlato: "Bondiola a la Mostaza",
    descripcion: "...",
    precio: 5300,
    categoria: "Cerdos",
  },
  {
    id: 56,
    nombrePlato: "Ñoquis Mixtos con Salsa Fileto",
    descripcion: "...",
    precio: 3300,
    categoria: "Pastas",
  },
  {
    id: 57,
    nombrePlato: "Ñoquis Mixtos con Salsa Parisiene",
    descripcion: "...",
    precio: 4600,
    categoria: "Pastas",
  },
  {
    id: 58,
    nombrePlato: "Tallarines Caseros (Bolognesa, Pesto)",
    descripcion: "...",
    precio: 4600,
    categoria: "Pastas",
  },
  {
    id: 59,
    nombrePlato: "Tallarines Caseros(Caligula: pestos, hongos y crema)",
    descripcion: "...",
    precio: 4600,
    categoria: "Pastas",
  },
  {
    id: 60,
    nombrePlato: "Ravioles de Espinaca y Pollo",
    descripcion: "...",
    precio: 4700,
    categoria: "Pastas",
  },
  {
    id: 61,
    nombrePlato: "Sorrentinos de Calabaza",
    descripcion: "...",
    precio: 4200,
    categoria: "Pastas",
  },
  {
    id: 62,
    nombrePlato: "Sorrentinos de Jamon y Muzzarella",
    descripcion: "...",
    precio: 4200,
    categoria: "Pastas",
  },
  {
    id: 63,
    nombrePlato: "Canelones de Espinaca y Pollo",
    descripcion: "...",
    precio: 4900,
    categoria: "Pastas",
  },
  {
    id: 64,
    nombrePlato: "Triptico Quattroccento",
    descripcion: "...",
    precio: 5500,
    categoria: "Pastas",
  },
  {
    id: 65,
    nombrePlato: "Lasaña",
    descripcion: "...",
    precio: 5700,
    categoria: "Pastas",
  },
  {
    id: 66,
    nombrePlato: "Spaghetti con Brocoli y Pesto",
    descripcion: "...",
    precio: 4600,
    categoria: "Pastas",
  },
  {
    id: 67,
    nombrePlato: "Tallarines Negros Mediterraneos",
    descripcion: "...",
    precio: 7100,
    categoria: "Pastas",
  },
  {
    id: 68,
    nombrePlato: "Rizo Negro",
    descripcion: "...",
    precio: 9600,
    categoria: "Pastas",
  },
  {
    id: 69,
    nombrePlato: "Spaghetti Quatroccento",
    descripcion: "...",
    precio: 9300,
    categoria: "Pastas",
  },
  {
    id: 70,
    nombrePlato: "Cintas Negras con Frutos de Mar",
    descripcion: "...",
    precio: 9600,
    categoria: "Pastas",
  },
  {
    id: 71,
    nombrePlato: "Arroz con Mariscos",
    descripcion: "...",
    precio: 16900,
    categoria: "Pastas",
  },
];

function App() {
  //console.log(Carta)
  console.log(Carta.filter((item) => item.categoria === "Pastas"));
  console.log(Carta.filter((item) => item.categoria === "Aves"));

  return (
    <>
      <h1>Quatroccento Restaurant</h1>
      <div>
        <ul>
          {Carta.filter((item)=>item.categoria == 'Cerdos').map((item) => ( 
            <li key={item.id}>
              {item.nombrePlato}
              <p>{item.descripcion}</p>
              <p>{item.precio}$</p>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}

export default App;
