export const Comidas = [
  {
    id: 1,
    nombre: "Pollo al Champiñon",
    descripcion: "Pechuga grillada, con salsa champiñon con papas noisette",
    precio: 6000,
    categoria: "aves",
    image: "",
  },
  {
    id: 2,
    nombre: "Pollo a la Plancha",
    descripcion: "Pechuga grillada con guarnicion",
    precio: 3400,
    categoria: "aves",
    image: "",
  },
  {
    id: 3,
    nombre: "Suprema",
    descripcion: "Con guarnicion",
    precio: 3800,
    categoria: "aves",
    image: "",
  },
  {
    id: 4,
    nombre: "Suprema Napolitana",
    descripcion: "Con guarnicion",
    precio: 4500,
    categoria: "aves",
    image: "",
  },
  {
    id: 5,
    nombre: "Chop Suey de Pollo",
    descripcion: "Verduras salteadas con pollo y salsa de soja y vino blanco",
    precio: 5400,
    categoria: "aves",
    image: "",
  },
  {
    id: 6,
    nombre: "Pechuga Rellena",
    descripcion: "Rellena de espinaca y queso, con papas españolas",
    precio: 6000,
    categoria: "aves",
    image: "",
  },
  {
    id: 7,
    nombre: "Pollo al Ajillo",
    descripcion: "Con papas españolas",
    precio: 6000,
    categoria: "aves",
    image: "",
  },
  {
    id: 8,
    nombre: "Abadejo con Salsa de Verdeo",
    descripcion: "Con papas rejilla",
    precio: 8000,
    categoria: "pescado",
    image: "",
  },
  {
    id: 9,
    nombre: "Abadejo con Salsa Roquefort",
    descripcion: "Con papas españolas",
    precio: 8000,
    categoria: "pescado",
    image: "",
  },
  {
    id: 10,
    nombre: "Abadejo con Salsa de Camarones",
    descripcion: "Con papas españolas",
    precio: 9600,
    categoria: "pescado",
    image: "",
  },
  {
    id: 11,
    nombre: "Salmon a la Plancha",
    descripcion: "Con guarnicion",
    precio: 11100,
    categoria: "pescado",
    image: "",
  },
  {
    id: 12,
    nombre: "Chop Suey de Salmon",
    descripcion: "Verduras salteadas con salmon, salsa de soja y vino blanco",
    precio: 12800,
    categoria: "pescado",
    image: "",
  },
  {
    id: 13,
    nombre: "Salmon Grille",
    descripcion: "Con guarnicion",
    precio: 14800,
    categoria: "pescado",
    image: "",
  },
  {
    id: 14,
    nombre: "Salmon con salsa Teriyaki",
    descripcion: "Con verduras salteadas",
    precio: 12800,
    categoria: "pescado",
    image: "",
  },
  {
    id: 15,
    nombre: "Pulpo la porcion",
    descripcion: "Con papas al natural",
    precio: 20900,
    categoria: "pescado",
    image: "",
  },
  {
    id: 16,
    nombre: "Pulpo y Langostinos a la parrilla Adobado",
    descripcion: "Con papas españolas",
    precio: 21700,
    categoria: "pescado",
    image: "",
  },
  {
    id: 17,
    nombre: "Salsa de Camarones",
    descripcion: "Para agregar",
    precio: 5500,
    categoria: "pescado",
    image: "",
  },
  {
    id: 18,
    nombre: "Matambrito de Cerdo",
    descripcion: "Con colchon de hojas verdes y verduras asadas",
    precio: 6600,
    categoria: "recomendado-chef",
    image: "",
  },
  {
    id: 19,
    nombre: "Brochette de Lomo",
    descripcion: "Con papas fritas y huevo revuelto",
    precio: 7000,
    categoria: "recomendado-chef",
    image: "",
  },
  {
    id: 20,
    nombre: "Entraña",
    descripcion: "Con colchon de hojas verdes",
    precio: 8800,
    categoria: "recomendado-chef",
    image: "",
  },
  {
    id: 21,
    nombre: "Milanesa",
    descripcion: "Con guarnicion",
    precio: 4100,
    categoria: "carnes",
    image: "",
  },
  {
    id: 22,
    nombre: "Milanesa Napolitana",
    descripcion: "Con guarnicion",
    precio: 4700,
    categoria: "carnes",
    image: "",
  },
  {
    id: 23,
    nombre: "Lomo a la Plancha",
    descripcion: "Con guarnicion",
    precio: 4600,
    categoria: "carnes",
    image: "",
  },
  {
    id: 24,
    nombre: "Chop Suey de Lomo",
    descripcion: "Descripcion...",
    precio: 6200,
    categoria: "carnes",
    image: "",
  },
  {
    id: 25,
    nombre: "Lomo a la Panceta",
    descripcion: "Con papas a la crema",
    precio: 7900,
    categoria: "carnes",
    image: "",
  },
  {
    id: 26,
    nombre: "Lomo al Champignon",
    descripcion: "Con papas noisette",
    precio: 7900,
    categoria: "carnes",
    image: "",
  },
  {
    id: 27,
    nombre: "Lomo a la Pimienta",
    descripcion: "Con papas a la crema",
    precio: 7500,
    categoria: "carnes",
    image: "",
  },
  {
    id: 28,
    nombre: "Lomo al Verdeo",
    descripcion: "Con papas rejilla",
    precio: 7500,
    categoria: "carnes",
    image: "",
  },
  {
    id: 29,
    nombre: "Lomo Strogonoff",
    descripcion: "Con spaghetti y hojas verdes",
    precio: 7500,
    categoria: "carnes",
    image: "",
  },
  {
    id: 30,
    nombre: "Lomo Ragu",
    descripcion: "Con salsa de Hongos",
    precio: 7900,
    categoria: "carnes",
    image: "",
  },
  {
    id: 31,
    nombre: "Saltimbocca a la Romana",
    descripcion: "Lomo relleno con jamon y queso marinado, y salvia con pure",
    precio: 7500,
    categoria: "carnes",
    image: "",
  },
  {
    id: 32,
    nombre: "Empanadas",
    descripcion: "De Carne cortada a cuchillo",
    precio: 650,
    categoria: "entradas",
    image: "",
  },
  {
    id: 33,
    nombre: "Rabas",
    descripcion: "Con Limon",
    precio: 5800,
    categoria: "entradas",
    image: "",
  },
  {
    id: 34,
    nombre: "Gambas al Ajillo",
    descripcion: "Langostinos salteados con ajo, vino blanco y pimenton",
    precio: 8000,
    categoria: "entradas",
    image: "",
  },
  {
    id: 35,
    nombre: "Provoleta Quattrocento",
    descripcion: "Queso gratinado con panceta y ceboolla de verdeo",
    precio: 2800,
    categoria: "entradas",
    image: "",
  },
  {
    id: 36,
    nombre: "Picada de Mariscos",
    descripcion:
      "Rabas, buñuelos de abadejo, gambas y pulpo.(Para dos personas)",
    precio: 15300,
    categoria: "entradas",
    image: "",
  },
  {
    id: 37,
    nombre: "Carpaccio de Salmon",
    descripcion:
      "Laminas de salmon crudo, con hojas verdes y vinagreta de limon",
    precio: 7600,
    categoria: "entradas",
    image: "",
  },
  {
    id: 38,
    nombre: "Milanesa de Mozarella",
    descripcion: "Mozarella rebozadas acompañada de salsa roja",
    precio: 2700,
    categoria: "entradas",
    image: "",
  },
  {
    id: 39,
    nombre: "Huevo Frito",
    descripcion: "Salsa sugerida: Fileto",
    precio: 500,
    categoria: "contornos",
    image: "",
  },
  {
    id: 40,
    nombre: "Papas Fritas",
    descripcion: "Salsa sugerida: bolognesa / pesto / caligula",
    precio: 2200,
    categoria: "contornos",
    image: "",
  },
  {
    id: 41,
    nombre: "Papas Españolas",
    descripcion: "Salsa sugerida: mixta",
    precio: 2200,
    categoria: "contornos",
    image: "",
  },
  {
    id: 42,
    nombre: "Pure de Papas",
    descripcion: "Salsa sugerida: verdeo",
    precio: 6200,
    categoria: "contornos",
    image: "",
  },
  {
    id: 43,
    nombre: "Pure de Calabaza",
    descripcion: "Salsa sugerida: cuatro quesos",
    precio: 7900,
    categoria: "contornos",
    image: "",
  },
  {
    id: 44,
    nombre: "Papas a la Crema",
    descripcion: "Con salsa mixta y queso gratinado",
    precio: 7500,
    categoria: "contornos",
    image: "",
  },
  {
    id: 45,
    nombre: "Papas Fritas con Huevo",
    descripcion: "Con salsa mixta y queso gratinado",
    precio: 7500,
    categoria: "contornos",
    image: "",
  },
  {
    id: 46,
    nombre: "Panache de Verduras",
    descripcion: "",
    precio: 7500,
    categoria: "contornos",
    image: "",
  },
  {
    id: 47,
    nombre: "Tortilla de Papa",
    descripcion: "Con brocoli y pesto",
    precio: 7500,
    categoria: "contornos",
    image: "",
  },
  {
    id: 48,
    nombre: "Ensalada de Hojas Verdes",
    descripcion: "Lechuga, rucula",
    precio: 2500,
    categoria: "ensaladas",
    image: "",
  },
  {
    id: 49,
    nombre: "Ensalada Mixta",
    descripcion: "Lechuga, tomate, zanahoria, huevo y cebolla",
    precio: 2500,
    categoria: "ensaladas",
    image: "",
  },
  {
    id: 50,
    nombre: "Ensalada Quatroccento",
    descripcion:
      "Lechuga, rucula, zanahoria, choclo, aceitunas verdes, champiñon, palmito, tomate, cebolla y queso parmesano",
    precio: 4000,
    categoria: "ensaladas",
    image: "",
  },
  {
    id: 51,
    nombre: "Ensalada Cesar",
    descripcion:
      "Hojas verdes, crotones, pollo salteado, queso parmesano y salsa cesar",
    precio: 4400,
    categoria: "ensaladas",
    image: "",
  },
  {
    id: 52,
    nombre: "Costilla a la Barcacoa",
    descripcion: "Con fritas(Solo domingo)",
    precio: 4500,
    categoria: "cerdos",
    image: "",
  },
  {
    id: 53,
    nombre: "Chop Suey de Cerdo",
    descripcion: "Descripcion...",
    precio: 5300,
    categoria: "cerdos",
    image: "",
  },
  {
    id: 54,
    nombre: "Carre con Compota de Ciruela",
    descripcion: "Con pure de manzana",
    precio: 5300,
    categoria: "cerdos",
    image: "",
  },
  {
    id: 55,
    nombre: "Bondiola a la Mostaza",
    descripcion: "Con papas chips",
    precio: 5300,
    categoria: "cerdos",
    image: "",
  },
  {
    id: 56,
    nombre: "Ñoquis Mixtos",
    descripcion: "Salsa sugerida: Fileto",
    precio: 3300,
    categoria: "pastas",
    image: "",
  },
  {
    id: 57,
    nombre: "Ñoquis Mixtos",
    descripcion: "Salsa sugerida: Parisiene",
    precio: 3300,
    categoria: "pastas",
    image: "",
  },
  {
    id: 58,
    nombre: "Tallarines Caseros",
    descripcion: "Salsa sugerida: Bolognesa / Pesto / Caligula",
    precio: 4600,
    categoria: "pastas",
    image: "",
  },
  {
    id: 60,
    nombre: "Ravioles de Espinaca y Pollo",
    descripcion: "Salsa sugerida: Mixta",
    precio: 4700,
    categoria: "pastas",
    image: "",
  },
  {
    id: 61,
    nombre: "Sorrentinos de Calabaza",
    descripcion: "Salsa sugerida: Verdeo",
    precio: 4200,
    categoria: "pastas",
    image: "",
  },
  {
    id: 62,
    nombre: "Sorrentinos de Jamon y Muzzarella",
    descripcion: "Salsa sugerida: Cuatro quesos",
    precio: 4200,
    categoria: "pastas",
    image: "",
  },
  {
    id: 63,
    nombre: "Canelones de Espinaca y Pollo",
    descripcion: "Con salsa mixta y queso gratinado",
    precio: 4900,
    categoria: "pastas",
    image: "",
  },
  {
    id: 64,
    nombre: "Triptico Quattroccento",
    descripcion:
      "Ñoquis mixtos, racioles de espinaca y pollo, sorrentinos de jamon y muzza. Salsa a eleccion",
    precio: 5500,
    categoria: "pastas",
    image: "",
  },
  {
    id: 65,
    nombre: "Lasaña",
    descripcion: "Con salsa mixta y queso gratinado",
    precio: 5700,
    categoria: "pastas",
    image: "",
  },
  {
    id: 66,
    nombre: "Spaghetti",
    descripcion: "Con Brocoli y Pesto",
    precio: 4600,
    categoria: "pastas",
    image: "",
  },
  {
    id: 67,
    nombre: "Tallarines Negros Mediterraneos",
    descripcion: "Con rabas, zuchini y tomate cherry",
    precio: 7900,
    categoria: "pastas",
    image: "",
  },
  {
    id: 68,
    nombre: "Rizo Negro",
    descripcion: "Con salsa de camarones",
    precio: 9600,
    categoria: "pastas",
    image: "",
  },
  {
    id: 69,
    nombre: "Spaghetti Quatroccento",
    descripcion: "Con salsa de salmon",
    precio: 9300,
    categoria: "pastas",
    image: "",
  },
  {
    id: 70,
    nombre: "Cintas Negras con Frutos de Mar",
    descripcion: "Talarines caseros con tinta de calamar, y frutos de mar",
    precio: 9600,
    categoria: "pastas",
    image: "",
  },
  {
    id: 71,
    nombre: "Arroz con Mariscos",
    descripcion: "Para dos personas",
    precio: 16900,
    categoria: "pastas",
    image: "",
  },
  {
    id: 59,
    nombre: "Ravioles Negros",
    descripcion: "Con salsa de camarones",
    precio: 9600,
    categoria: "pastas",
    image: "",
  },
  {
    id: 72,
    nombre: "Dunas Malbec",
    descripcion: "",
    precio: 5000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 73,
    nombre: "Entretantos",
    descripcion: "Cosecha Catamarqueña",
    precio: 6900,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 74,
    nombre: "Luigui Bosca Malbec",
    descripcion: "",
    precio: 10600,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 75,
    nombre: "Fabre Montmayou",
    descripcion: "Terruño reserva",
    precio: 7000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 76,
    nombre: "Perro Callejero",
    descripcion: "",
    precio: 8000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 77,
    nombre: "Cordero Con Piel de Lobo",
    descripcion: "",
    precio: 6500,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 78,
    nombre: "Seismiles",
    descripcion: "Cabernet / Malbec / Syirah",
    precio: 4800,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 79,
    nombre: "Alamos Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 7200,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 80,
    nombre: "Nicasia Vineyrad Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 8400,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 81,
    nombre: "Saint Felicien Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 10200,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 82,
    nombre: "DV Catena Cabernet Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 14500,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 83,
    nombre: "El Gran Enemigo",
    descripcion: "Bodega Catena Zapata",
    precio: 39000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 84,
    nombre: "Angelica Zapata",
    descripcion: "Bodega Catena Zapata",
    precio: 32000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 85,
    nombre: "Dv Catena Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 19900,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 86,
    nombre: "Benjamin Malbec",
    descripcion: "Bodega Catena Zapata",
    precio: 5100,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 87,
    nombre: "Trumpeter Malbec",
    descripcion: "",
    precio: 8600,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 98,
    nombre: "Argentino",
    descripcion: "",
    precio: 69000,
    categoria: "vinos-tintos",
    image: "",
  },
  {
    id: 88,
    nombre: "Baron B",
    descripcion: "Con salsa de salmón",
    precio: 21000,
    categoria: "champagne",
    image: "",
  },
  {
    id: 89,
    nombre: "Salentein",
    descripcion: "Extra Brut",
    precio: 9500,
    categoria: "champagne",
    image: "",
  },
  {
    id: 90,
    nombre: "Chandon",
    descripcion: "Bodega chandón",
    precio: 9500,
    categoria: "champagne",
    image: "",
  },
  {
    id: 91,
    nombre: "Gaseosas",
    descripcion: "Coca cola(comun o zero), sprite, fanta",
    precio: 1400,
    categoria: "bebidas sin alcohol",
    image: "",
  },
  {
    id: 92,
    nombre: "Aguas Saborizadas",
    descripcion: "Aquarius",
    precio: 1400,
    categoria: "bebidas sin alcohol",
    image: "",
  },
  {
    id: 93,
    nombre: "Paso de los toros",
    descripcion: "Agua tonica o pomelo",
    precio: 1400,
    categoria: "bebidas sin alcohol",
    image: "",
  },
  {
    id: 94,
    nombre: "Agua",
    descripcion: "con gas y sin gas",
    precio: 1200,
    categoria: "bebidas sin alcohol",
    image: "",
  },
  {
    id: 95,
    nombre: "Heineken",
    descripcion: "",
    precio: 4700,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 96,
    nombre: "Imperial",
    descripcion: "",
    precio: 3600,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 97,
    nombre: "Salta Negra",
    descripcion: "",
    precio: 3600,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 99,
    nombre: "Corona",
    descripcion: "",
    precio: 5200,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 100,
    nombre: "Corona monjita",
    descripcion: "",
    precio: 2500,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 101,
    nombre: "Stella",
    descripcion: "",
    precio: 4700,
    categoria: "bebidas con alcohol",
    image: "",
  },
  {
    id: 120,
    nombre: "Chacabuco Dulce",
    descripcion: "",
    precio: 5500,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 121,
    nombre: "Seis Miles Chardonay",
    descripcion: "Cosecha Catamarqueña-Tinogasta",
    precio: 4800,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 102,
    nombre: "Saint Felicien Chardonay",
    descripcion: "",
    precio: 10200,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 103,
    nombre: "Entretantos Blanc De Blanc",
    descripcion: "Cosecha Catamarqueña",
    precio: 6900,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 104,
    nombre: "Nicasia Blanco",
    descripcion: "Bodega Catena Zapata",
    precio: 7200,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 105,
    nombre: "Alamo Chardonay",
    descripcion: "Bodega Catena Zapata",
    precio: 7200,
    categoria: "vinos-blancos",
    image: "",
  },
  {
    id: 106,
    nombre: "Fernet",
    descripcion: "Medida",
    precio: 1800,
    categoria: "aperitivos",
    image: "",
  },
  {
    id: 122,
    nombre: "Blenders",
    descripcion: "Medida",
    precio: 1400,
    categoria: "aperitivos",
    image: "",
  },
  {
    id: 123,
    nombre: "Chivas",
    descripcion: "Medida",
    precio: 1400,
    categoria: "aperitivos",
    image: "",
  },
  {
    id: 107,
    nombre: "Helados Cantegrill",
    descripcion:
      "Chocolate, frutilla, vainilla, Dulce De leche, Crema americana, Limón y Frutos del bosque [2 bochas]",
    precio: 2000,
    categoria: "postres",
    image: "",
  },
  {
    id: 108,
    nombre: "Flan de Huevo",
    descripcion: "...",
    precio: 2000,
    categoria: "postres",
    image: "",
  },
  {
    id: 109,
    nombre: "Ensalada De Frutas",
    descripcion: "...",
    precio: 2000,
    categoria: "postres",
    image: "",
  },
  {
    id: 110,
    nombre: "Panqueque de Dulce de Leche",
    descripcion: "...",
    precio: 1800,
    categoria: "postres",
    image: "",
  },
  {
    id: 111,
    nombre: "Peras al Vino",
    descripcion: "...",
    precio: 1800,
    categoria: "postres",
    image: "",
  },
  {
    id: 112,
    nombre: "Dulces Regionales con Helado o Queso",
    descripcion: "...",
    precio: 2300,
    categoria: "postres",
    image: "",
  },
  {
    id: 113,
    nombre: "Tiramisu",
    descripcion: "...",
    precio: 2300,
    categoria: "postres",
    image: "",
  },
  {
    id: 114,
    nombre: "Tatin de Manzana",
    descripcion: "...",
    precio: 2300,
    categoria: "postres",
    image: "",
  },
  {
    id: 115,
    nombre: "Brownie con Helado y Frutos Rojos Bañado en Baileys",
    descripcion: "...",
    precio: 2300,
    categoria: "postres",
    image: "",
  },
  {
    id: 116,
    nombre: "Brownie con Helado de Mascarpone y Frutos del Bosque",
    descripcion: "...",
    precio: 2300,
    categoria: "postres",
    image: "",
  },
  {
    id: 117,
    nombre: "Ensalada de Frutas con Helado",
    descripcion: "...",
    precio: 2700,
    categoria: "postres",
    image: "",
  },
  {
    id: 118,
    nombre: "Panqueque Quattroccento",
    descripcion: "...",
    precio: 3100,
    categoria: "postres",
    image: "",
  },
  {
    id: 119,
    nombre: "Adicional de dulce de leche o crema",
    descripcion: "...",
    precio: 500,
    categoria: "postres",
    image: "",
  },
];